services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    env_file:
      - path: Backend/.env
        required: false
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: portfolio/Dockerfile
      args:
        BUILD_CONFIGURATION: development
    depends_on:
      - backend
    ports:
      - "8080:80"
